service: backend-test

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
